FROM photonos-docker-local.artifactory.eng.vmware.com/photon5-amd64@sha256:0ad943d3f5bfee87749bd05f52c1c0d0a8fad4835c624e8b94893940af018b8e as builder-base

# Installing Go
COPY images/go1.18.10.linux-amd64.tar.gz /tmp/
RUN rm -rf /usr/local/go && tar -C /usr/local -xzf /tmp/go1.18.10.linux-amd64.tar.gz

# # Setting up Proxies
# ENV HTTP_PROXY $http_proxy
# ENV HTTPS_PROXY $https_proxy

# Install the necessary dependencies
RUN tdnf update -y && \
    tdnf install -y git make gcc glibc-devel binutils gawk linux-api-headers

# Add the ddptool
ADD images/ddptool-1.0.1.12.tar.gz /tmp/ddptool/

# Clone the hwdata repo
RUN git clone https://github.com/vcrhonek/hwdata.git /tmp/hwdata
